//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Artista.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Artista {
	public String Nombre;
	public Date FechaNacimiento;
	public Date FechaDefuncion;
	public String Pais;
	public String Epoca;
	public String EstiloPrincipal;
	public String Descripcion;
}
