//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Categoria.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Categoria {
	public String Tipo;
	public String Pertenencia;
}
