//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ColeccionPermanente.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class ColeccionPermanente {
	public Date FechaAdquisición;
}
