//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Costo.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Costo {
	public Object Expocisión;
	public Object Almacen;
}
