//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Escultura.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Escultura {
	public String Altura;
	public String Peso;
	public String Estilo;
}
