//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Objeto.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Objeto {
	public String NúmeroIdentificación;
	public String Artista;
	public Date AnñoCreación;
	public String Titulo;
	public String Descripción;
}
