//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Origen.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Origen {
	public String Pais;
	public String Cultura;
	public String Epoca;
}
