//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pertenencia.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Pertenencia {
	public String ObjetoPrestad;
	public Object Colección Permanente;
}
