//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pintura.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Pintura {
	public String TipoPintura;
	public String Soporte;
	public String Estilo;
}
