//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Prestado.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Prestado {
	public String NombreColección;
	public Date FechaEntrega;
	public Date FechaDeevolución;
}
