//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tipo.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Tipo {
	public String Pintura;
	public String Escultura;
	public Object Otros;
}
