//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Agencia.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Agencia {
	public String Direccio;
	public String Nombre;
}
