//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Auto.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Auto {
	public String Garage;
	public String Matricula;
	public String Modelo;
	public String Color;
	public String Marca;
	public Object Costo;
	public Object Entregado;
}
