//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Cliente {
	public String DPI;
	public String Nombre;
	public String Dirección;
	public String Telefono;
	public void Identificar() {
	
	}
}
