//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DetalleReserva.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class DetalleReserva {
	public Date FechaInicio;
	public Date FechaFin;
	public Object CostoGasolina;
}
