//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reserva.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Reserva {
	public String Costo;
}
