//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Conductor.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Conductor {
	public String DPI;
	public void Ingrasar() {
	
	}
}
