//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Administrativo.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Administrativo {
	public Object 1%Sueldo base;
}
