//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Empledo.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Empledo {
	public String DPI;
	public String Nombre;
	public String Direcció;
	public String NúmeroTelefono;
	public Date FechaContratacion;
}
