//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Encargado.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Encargado {
	public Integer Numerocomercintes;
	public Object 1%SueldoBase;
}
