//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ercial.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class ercial {
	public Object Attribute1;
}
