//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Limpiador.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Limpiador {
	public Object 0.5%SueldoBase;
}
