//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Planilla.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Planilla {
	public String Contrato;
	public String Despido;
}
