//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sueldo.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Sueldo {
	public String SueldoBase;
	public String HoraExtra;
}
