//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tipos.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Tipos {
	public String Limpiador;
	public String Comercial;
	public String Administrativo;
	public String Encaargado;
}
