//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Empresa de transporte.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Empresa de transporte {
	public Object conductor;
}
