//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sueldo.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Sueldo {
	private Object Sueldo base;
	public Object Hora;
	public void Cobrar() {
	
	}
}
