//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transporte.java
//  @ Date : 28/03/2015
//  @ Author : 
//
//




public class Transporte {
	public String colectivo;
	public String no colectivo;
	public String mecrcancia;
	public Object mercancia peligroso;
	public void transportar() {
	
	}
}
